language: python
python:
- '3.7'
services:
- docker
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


before_install:
- "./ci/before_install.sh"
install:
- "./ci/install.sh"

before_script:
- echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
- "./ci/add_docker.sh"
script:
- "./ci/test.sh"
- "./ci/after_test.sh"
- "./ci/build.sh"

deploy:
- provider: script
  script: bash ./ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master


cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/client/node_modules


env:
  global:
  - NODE_JS_VERSION=10
  - secure: f8sK/EIzj6t7eWy57yScKPetHW+2o4pWpHRB2VsgFLesrqNeDg9QwDyVYrule4tCU1TBFtwzRJyOufZr3BWb1rnKcPftNW/FcfO9hRqRBR37tQTkGJo7UHFQ6bwrnCz0iFheU1Xwko3Ajp5z9QG0dCE9ps1Upp2f4Iez7Pz66n5VAy/fxmhWDHLePW3le0GKDdMj009JEpcXHGry49IBu3E4Ul0F3FscnBpL2B2KOlQ92l1j2lAkQPzTetntKcLVs7+PwhgLTq0dQcp7TB4GUTU2GtpJzX4KWPe9m1+MQHPcoIr6S1zioCDZbOiaNpAJWEeGSKzS5scycC6h+l3ZVw2UqxAdanhcLuXDFm6LxPH1LI/A+etbzJ/6Tk+atzZ9GFSN85Rw4cmSdaUbO+Byb25nqiz3+K62LtSD6YSlAVFysA01PQ3R9xPS2HNlpteujMl5Y5nFLm2HbpQZ7sE+sXdjH4wyqjxvVJ2xJ6QKzNxN/0zN2tGblcPLb5OmYmErxRQGQHZKfYO8hA7lyOzqwQmIZxe1brWlziE1CDFaNd9teh2FqBi+V15RFAe5I2RlxWz0oMFJC/L3ToF8c59UBgdU32vOLnqrLbxbpoI5ApQ0MpNcYiZ93NaAgkxQQFKmiL3z6BD3sFSIpxaTpP1Iu9FDe4EcVNIXThwzgWwOphU=
  - secure: mFYmYjlxphqhjdyGU0VBci2u0+KtaZaOqdqF18mLrJBq+yWjdCVaMhzlyQYTZlUoJKHkxR1NBTg8tDGMU+GS24RKMeziHMGtfbL0CSJu5DxZMRpmBj5sIH94aFsCo53WCHKtk6WqsFPztBzwCRr/EPW5CfQ3Emn+WUGB7hQ9SXPkuCIHj9UxnTQGQfG1q+x3tn0Gsr2xcr18arQjKAnA7ldS8TktYRNw/HAVd169EH54BZSZOjCU3/tRd4TmMgLea6EQ7Nc5rYk+ySKFpncEQccrQOx9EC0cf5kCafjdMQvyxt//b4jNKfy14h+8P0yAU/fqJkOZ5gq6d9E4jtHegoTTnhFdDSyCsHqFuYE7t9ZfPrNkIesGqOILZ6AaIeZTs2ANVX7EDShbERZzEICSyJ2ahw5OnkLW4Y39qaqOSyQPsU1RtoNEq4dHJA9MaiUz+LfSAb1D/UxoQwk6Yg1IOq7qUSwTgzbuxFmXov01ZSQ2EIT+/hsZaPHtLbc6P5hCu9Xem7CGht4SSqglTCMQFoPr55zbBu6qy86iwf7eFhySYIgt3BM6QMqm4PgsRkfW0IYzkRyGOAHVdmrDsf+NPzd303ZEZBn3KYwk0rRm4DbnMUHiX1iQY3OeKvOo/cIeiOz3dnJKgShfjfzjNSNYzvd1dayXDsvtqQwLBON7Ktc=
  - secure: B12pWObP3gZJ8tBuhJDiXTNxRO3fP2EDSB1PluKstUWURu716FHVG2bfwfyySezYxU0zIwIrM1fxT0g+dXepcVcf1BEP8RLzN3cUTA11r9lCY30TMJewu5Ox7VSH/Y2Ow1N71BKygmrVfFzcdSnaRWw+fcks9PqvG844Q9Ebpu0RVhHnc5K2kYKIhL1AMTPZssVj71VxTthiiSKWy+KPdMSfQdOEu3qe/0JhB+buOqnm37/XhL86eSuGBJKr9Y0iTzJ34UKatxReze/GH335pzTGjA1gJB60HWb7ViBOu3y3o/JQWTBgTOuZUwogEo7duQWqHoY2UwycfljL9co2BjeUrdp5s7WLAVWqLw8R6covAjbm2/ma8AHm+BcdmLPGOEKx95dp6y91jaq5R4EN4e6r2kVYUn+Uo2vRTubWpiP3px+gN0KNVW4Fc8xgJoiNzDXuaQoLH1DkJl7WojrMoyIJcCzjXTcvPm1XfKa9zOp9A93AZZ9PcaH0z0JiR2+8jgeuzvZ0uI0DkUxFgYUzzMWAB72WznKBW2JGcYPrTAerA/S+/G500xS+10zJwA6JDrPtZ8qQYpL1/ipVYMSho2dJ/rQaIxQKw5VexB6iyepS92VsR64ljAaZ2w26Gv3CqhB+pIw9O9t+8yizRlX06jo0XT15pDx3eJpChvdRvrw=
  - secure: Iuqv5mNRNe3sqHFRMLYAb0kOsH8hOQOLYSuO3LdGHUQFfzbqEDVRtVuy3+3TFqgr5e+wrVq7hZznlWEr1hGjitjWS2JEzwgvvdW2ZcS1vKPbLQAVQT7ECmbpBqNxOANqhSIKO8fVst5fxhGFVmFVZHF0HIRYFhREMZOdN6aUCf0AfDmvSLc/GhYbJoq9JbiJBrEf1IJeQwT0vZmPV1D6zAhcCCFSRY25Ysczi13q1LN/sNVvDELophghe7/mRH60+iInuuwUM0q8Bkxuili5E3CjszXckc91Oi8gQhxyCHVIeLh5mcLM6Svp2/od+fz9qM/0u4QHT1wje/m+yuXi9/RK9mRe3t0o1r+Ay+Z4a7d3Oo4rxzXdDvmZ2/JANwpaCTNT5OESUIljrj9hDvOyGJqwyqD7nKBSqwRs1WUZL99AKqkdPOF8OL/MheQpnIwhcKCVX8JyHHyBBFNZqlauzC0IhUiXb4+J678tsMEIj0fpMm5JZ8iecq2k+REyUMARCkgXeLwzuXIs+5YqWQM5MtVXYHLjNiVakQVJJHX3RUK04ye4Yhu+vYFn8XYhtSfRdioeeJmpvFmaJIVSWn9oiri2E3b0HrNOPzwWJgWAeuYuIMwTr9zn6k2ui73Mcr+wR8Vcw5KWJDy0mnfdIrybQV9m5/FEuFXWWg0kqZh/pE0=
  - secure: zrYRu8YVSbZv4p75B3SFtF+9Nf/hnQRHO6EXSVRpoVl8bpRt4N63C5WVC4y4qKXcqn4404ZJTKmcjJKfCNPsSI3NgqeNdemBDUUP0iNw7yaC5Qg4vZ+FgAWnbxCmNRJreTkXz3aQk6xJT07ugChFkQT2dwiJHqvV6l4myB/rHvokR3DqRHbzjeTObkbUx99OS0+J+GR1TUv+1vR9bS+QgT7ejXkXzs5SfHFut2SNENtRjlj28waexdSLh9Lv95nPv9KeN+CXGhFOqn7UX4UCoZ2XyqBNY5FbP46EaWZ224tN+QvZ1hYg1Xzd00xR3z5ATaxnrGcxzWmPdd2t1UO7F6SJxKREoKp+YkDfXGfd4Me5mLQSQ9zNMJL8y1xuj1j5CayoAwrdeIF4pieRMTL/gPyb0drvsra/FlyhtP7pUNZn7Ap81Wmj0KjJw+f8GZjDBWDYfk+616qtWWJQ8umOt6ddxo5Qw4hbs+sEpgT8C9ROpVH4M8emzfnK1GHlNfv50OiwJTJqCs9a861v+M7ft4AIHBMJWdvxro/eUcKWFDtxD8Xk7u12NJyWC5b7tcZmLI7F1Rb2i8Tcp3PAN0tS0YYmSwborXDLLgDU7sNiC19P7umVXJnw6nmIrIhHAaRnlXLWAVWncRXb7BNLL7rZFAxcMA4wrG2SZnPvnM/vftQ=
