# Generated by Django 2.2.6 on 2019-10-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainimage',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
