# Generated by Django 2.2.6 on 2019-10-29 23:16

from django.db import migrations


def load_dataset(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    MathSymbol = apps.get_model("server", "MathSymbol")
    ClassificationModel = apps.get_model("server", "ClassificationModel")
    print(MathSymbol, ClassificationModel)

def drop_dataset(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_trainimage_locked'),
    ]

    operations = [
        migrations.RunPython(load_dataset, drop_dataset),
    ]
