# Generated by Django 2.2.6 on 2019-11-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20191109_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
