# Generated by Django 2.2.6 on 2019-11-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20191111_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathsymbol',
            name='latex',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
