# Generated by Django 2.2.6 on 2019-11-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20191125_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='pytorch',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
