# Generated by Django 2.2.6 on 2019-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20191125_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainimage',
            name='features',
            field=models.BinaryField(blank=True, editable=True),
        ),
    ]
