# Generated by Django 2.2.6 on 2019-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20191130_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationmodel',
            name='accuracy',
            field=models.FloatField(default=0.9),
        ),
    ]
