version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure
  tex2svg:
    image: hoff97/tex2svg
    restart: always
  server:
    image: hoff97/detext-server
    volumes:
      - static-django:/usr/src/app/django
    depends_on:
      - db
      - tex2svg
    restart: on-failure
  client:
    image: hoff97/detext-client
    volumes:
      - static-content:/usr/src/app/public
    restart: on-failure
  nginx:
    image: hoff97/detext-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "server"
      - "client"
      - "tex2svg"
    volumes:
     - static-content:/usr/src/app/public
     - static-django:/usr/src/app/django
     - letsencrypt:/etc/letsencrypt/
    restart: on-failure

volumes:
  postgres_data:
  static-content:
  static-django:
  letsencrypt:
