version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  server:
    image: hoff97/detext-server
    command: bash -c "python /code/manage.py migrate --settings=detext.settings_prod && python /code/manage.py runserver --settings=detext.settings_prod 0.0.0.0:8000"
    volumes:
      - static-django:/usr/src/app/django
    depends_on:
      - db
  client:
    image: hoff97/detext-client
    volumes:
      - static-content:/usr/src/app/public
  nginx:
    image: hoff97/detext-nginx
    ports:
      - "80:80"
    depends_on:
      - "server"
      - "client"
    volumes:
     - static-content:/usr/src/app/public
     - static-django:/usr/src/app/django

volumes:
  postgres_data:
  static-content:
  static-django: