name: Test backend

on: []

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd server
        pip install -r requirements.txt
    - name: Run tex2svg
      run: |
        docker run -d --name tex2svg -p 0.0.0.0:9000:8000 hoff97/tex2svg

    - name: Run tests with coverage
      run: |
        cd server
        coverage run --source='.' manage.py test detext.server detext/tests
        coverage xml
        cd ..
    - name: Stop tex2svg
      run: |
        docker stop tex2svg
    - uses: codecov/codecov-action@v1
      with:
        file: ./server/coverage.xml
        flags: backend