name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Add docker machine
      run: |
        docker-machine create \
          --driver generic \
          --generic-ip-address=$DO_IP \
          --generic-ssh-user root \
          --generic-ssh-key /HOME/.ssh/id_rsa \
          detext
        docker-machine ls
#    - name: Build frontend container
#      run: |
#        cd client
#        docker build -t hoff97/detext-client
#    - name: Build backend container
#      run: |
#        cd server
#        docker build -t hoff97/detext-server
#    - name: Build nginx container
#      run: |
#        cd nginx
#        docker build -t hoff97/detext-nginx